# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f8258600e4fbb801f95c99ada88e91106abc7fc69edd9fb50227b1133777d88c75685796308f7682519e2d2c258c927c2ca964d068486183a6b89a563ab30047

test:
  secret_key_base: f32326c399c0512ef7f7fb2f38a080fba6c08e30a0258146b6778379a9cf7618fcc6871bd09c5ba20c622275c5d3cec6f93d03248468abcde17fa8c1482f6120

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
